name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validates code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build . -t books-backend

      - name: Run tests
        run: |
          docker run --rm books-backend vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build and push Docker image
        run: |
          docker build . -t books-backend
          docker tag books-backend:latest ${{ secrets.DOCKER_HUB_USER }}/books-backend:latest
          docker push ${{ secrets.DOCKER_HUB_USER }}/books-backend:latest
