services:
    books-backend:
        container_name: 'books-backend'
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www
        networks:
            - books-network
        depends_on:
            - mysql
        environment:
            - XDEBUG_MODE=${XDEBUG_MODE}

    nginx:
        container_name: 'books-nginx'
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
        ports:
            - 8090:80
        depends_on:
            - books-backend
        networks:
            - books-network

    mysql:
        container_name: 'mysql'
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - '3308:3306'
        environment:
            MYSQL_DATABASE: 'booksdb'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ""
        networks:
            - books-network



networks:
    books-network:
        driver: bridge
